---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Add hosts to inventory
      ansible.builtin.add_host:
        name: "{{ item }}"
        ansible_host: "{{ item }}"
        ansible_ssh_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
        ansible_ssh_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
        groups: servers
      loop: "{{ lookup('env', 'LINUX_HOSTS').split(',') }}"

- name: Running provisioning
  hosts: servers
  become: true
  gather_facts: yes

  tasks:
    - include_role:
        name: docker-rockyl
      vars:
        user_add_docker_group: "{{ lookup('env', 'DOCKER_USER') }}"
        docker_bip: '169.254.0.1/16'
        docker_data_root: '/opt/docker-root-dir'

