---
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default
dependency:
  name: galaxy
driver:
  name: docker
provisioner:
  name: ansible
  # env:
  #   ANSIBLE_VERBOSITY: 3
verifier:
  name: ansible
platforms:
  - name: test-multi-01
    hostname: test-multi-01
    image: rockylinux:9-systemd
    pull: false
    command: "/usr/sbin/init"  # to use systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    # tmpfs:
    #   - /run
    #   - /tmp
    # tty: true
    privileged: true
    environment:
      container: docker
    pre_build_image: true
    networks:
      - name: test_network
